version: '3'
services: 

# Pulling the the image(my-app:verion(1.3)) from AWS-ECR
    my-app: 
        image: node-app
        ports: 
            - 3300:3300
# docker run -d -p 127.0.0.1:27018:27017 -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=root --name mongodb --net mongo-network mongo
    mongodb:
        image: mongo
        ports: 
            - 127.0.0.1:27017:27017
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=root

# docker run -d -p 8081:8081 -e ME_CONFIG_MONGODB_ADMINUSERNAME=admin -e ME_CONFIG_MONGODB_ADMINPASSWORD=root  -e ME_CONFIG_MONGODB_SERVER=mongodb --name mongo-express --net mongo-network mongo-express
    mongo-express:
        image: mongo-express
        ports: 
            - 8081:8081
        environment: 
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=root
            - ME_CONFIG_MONGODB_SERVER=mongodb